version: '3'

services:
  z-file:
    container_name: z-file
    networks:
      - traefik
    restart: always
    expose:
      - '8080'
    volumes:
      - './db:/root/.zfile-v4/db'
      - './logs:/root/.zfile-v4/logs'
      - './file:/data/file'
      - './application.properties:/root/application.properties'
    image: zhaojun1998/zfile
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.miniflux.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.miniflux.entrypoints=websecure"
      - "traefik.http.routers.miniflux.tls=true"

networks:
  traefik:
    external: true